### ISSUE TITLE
Pressing F5 resets the app

### ISSUE THREAD

**Issue by jtiz003** [uvicgse/project-seed#11]
Regardless of where you are within the app, pressing F5 resets the whole app and takes you back to the login screen. This should not be possible as it may produce unexpected behavior for the rest of the app and gives the impression the app is not stable.

**Steps to reproduce:**

1. Sign in or continue without sign in on Visual Git
2. Press F5
3. Observe app reset

**Expected Output:**

F5 no longer takes you back to the login screen

**Comment by jbenning97** [comment]
F5 should do nothing

**Comment by jtiz003** [comment]
Resolved by both teams in sprint 1
