### ISSUE TITLE
Optional console logging

### ISSUE THREAD

**Issue by jtiz003** [uvicgse/project-seed#23]
There are a significant number of console logs appearing throughout the project.
It would be nice to have a way of enabling and disabling console logs when necessary.
This would make debugging easier.

![image](https://user-images.githubusercontent.com/22312351/57658113-847d7400-7592-11e9-8889-d144920113a1.png)

**Comment by jamshale** [comment]
Here is a stackoverflow page that explains a solution to this issue:

https://stackoverflow.com/questions/1215392/how-to-quickly-and-conveniently-disable-all-console-log-statements-in-my-code/27797684

**Comment by jtiz003** [comment]
This issue has been resolved in a previous PR
